name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build0:
    name: Build and analyze backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: | 
            cd ./java-backend
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kshitiz-mhto_mono_repo_demo


  # sonarcloud1:
  #   name: SonarCloud-for-ui
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'npm'
          cache-dependency-path: ./ui/package-lock.json
      - name: Install dependencies
        working-directory: ./ui
        run: |
          npm install
      - name: Format and Lint all files
        working-directory: ./ui
        run: |
          npm test
          npm run cover
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ui/
          args: >
            -Dsonar.projectKey=kshitiz-mhto_mono_repo_demo
            -Dsonar.organization=kshitiz-mhto
            -Dsonar.projectName=KalaUI
  
  # sonarcloud2:
  #   name: SonarCloud-for-py
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install Python dependencies
        working-directory: ./python-client
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          pip install tox
      - name: Run tox
        working-directory: ./python-client
        run: tox -e py --cov-report term --cov-report xml:coverage.xml 
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: python-client/
          args: >
            -Dsonar.projectKey=kshitiz-mhto_mono_repo_demo
            -Dsonar.organization=kshitiz-mhto
            -Dsonar.projectName=KalaPy
            -Dsonar.python.coverage.reportPaths=coverage.xml